const swaggerDoc = {
  openapi: '3.0.0',
  info: {
    title: 'Primavera V10 API',
    version: '2.0.0',
    description: 'REST API para dados do ERP Primavera V10 Executive - Analytics, Vendas, Compras, Stock, RH, Financeiro, Base. Read-only.',
  },
  servers: [{ url: '/api' }],
  components: {
    securitySchemes: {
      basicAuth: {
        type: 'http',
        scheme: 'basic',
        description: 'Basic Auth (user:password)',
      },
      apiKey: {
        type: 'apiKey',
        in: 'header',
        name: 'x-api-key',
        description: 'API Key no header x-api-key',
      },
    },
  },
  security: [
    { basicAuth: [] },
    { apiKey: [] },
  ],
  paths: {
    // ===== SISTEMA =====
    '/health': { get: { tags: ['Sistema'], summary: 'Health check + info BD', responses: { 200: { description: 'OK' } } } },
    '/health/tables': { get: { tags: ['Sistema'], summary: 'Listar todas as tabelas da BD', responses: { 200: { description: 'OK' } } } },
    '/health/tables/{nome}/columns': { get: { tags: ['Sistema'], summary: 'Colunas de uma tabela', parameters: [{ name: 'nome', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },

    // ===== BASE (Entidades Mestras) =====
    '/base/familias': { get: { tags: ['Base'], summary: 'Listar familias de artigos', responses: { 200: { description: 'OK' } } } },
    '/base/subfamilias': { get: { tags: ['Base'], summary: 'Listar subfamilias', parameters: [{ name: 'familia', in: 'query', schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/marcas': { get: { tags: ['Base'], summary: 'Listar marcas', responses: { 200: { description: 'OK' } } } },
    '/base/modelos': { get: { tags: ['Base'], summary: 'Listar modelos', parameters: [{ name: 'marca', in: 'query', schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/armazens': { get: { tags: ['Base'], summary: 'Listar armazens', responses: { 200: { description: 'OK' } } } },
    '/base/armazens/{id}': { get: { tags: ['Base'], summary: 'Detalhes de um armazem', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/unidades': { get: { tags: ['Base'], summary: 'Listar unidades de medida', responses: { 200: { description: 'OK' } } } },
    '/base/vendedores': { get: { tags: ['Base'], summary: 'Listar vendedores', responses: { 200: { description: 'OK' } } } },
    '/base/vendedores/{id}': { get: { tags: ['Base'], summary: 'Detalhes do vendedor', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/vendedores/{id}/vendas': { get: { tags: ['Base'], summary: 'Resumo de vendas do vendedor', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/zonas': { get: { tags: ['Base'], summary: 'Listar zonas geograficas', responses: { 200: { description: 'OK' } } } },
    '/base/condpag': { get: { tags: ['Base'], summary: 'Condicoes de pagamento', responses: { 200: { description: 'OK' } } } },
    '/base/moedas': { get: { tags: ['Base'], summary: 'Listar moedas', responses: { 200: { description: 'OK' } } } },
    '/base/iva': { get: { tags: ['Base'], summary: 'Tabela de IVA', responses: { 200: { description: 'OK' } } } },
    '/base/series': { get: { tags: ['Base'], summary: 'Series de documentos', parameters: [{ name: 'tipoDoc', in: 'query', schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/base/tiposdoc': { get: { tags: ['Base'], summary: 'Tipos de documento', responses: { 200: { description: 'OK' } } } },

    // ===== CLIENTES =====
    '/clientes': { get: { tags: ['Clientes'], summary: 'Listar clientes', parameters: [
      { name: 'search', in: 'query', schema: { type: 'string' }, description: 'Pesquisa geral (codigo, nome, contribuinte, email, telefone)' },
      { name: 'nome', in: 'query', schema: { type: 'string' }, description: 'Filtrar por nome' },
      { name: 'contribuinte', in: 'query', schema: { type: 'string' }, description: 'Filtrar por NIF' },
      { name: 'localidade', in: 'query', schema: { type: 'string' }, description: 'Filtrar por localidade' },
      { name: 'pais', in: 'query', schema: { type: 'string' }, description: 'Filtrar por pais' },
      { name: 'situacao', in: 'query', schema: { type: 'string' }, description: 'Filtrar por situacao (Activo, etc)' },
      { name: 'condpag', in: 'query', schema: { type: 'string' }, description: 'Filtrar por condicao pagamento' },
      { name: 'zona', in: 'query', schema: { type: 'string' } },
      { name: 'vendedor', in: 'query', schema: { type: 'string' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/clientes/{id}': { get: { tags: ['Clientes'], summary: 'Detalhes do cliente', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/clientes/{id}/documentos': { get: { tags: ['Clientes'], summary: 'Documentos do cliente', parameters: [
      { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
      { name: 'tipoDoc', in: 'query', schema: { type: 'string' }, description: 'Tipo documento (FA, EC, NC...)' },
      { name: 'serie', in: 'query', schema: { type: 'string' } },
      { name: 'totalMin', in: 'query', schema: { type: 'number' }, description: 'Valor minimo' },
      { name: 'totalMax', in: 'query', schema: { type: 'number' }, description: 'Valor maximo' },
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/clientes/{id}/saldo': { get: { tags: ['Clientes'], summary: 'Saldo conta corrente', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/clientes/{id}/pendentes': { get: { tags: ['Clientes'], summary: 'Documentos pendentes detalhados', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/clientes/analytics/resumo': { get: { tags: ['Clientes Analytics'], summary: 'Resumo geral clientes', responses: { 200: { description: 'OK' } } } },
    '/clientes/analytics/top-devedores': { get: { tags: ['Clientes Analytics'], summary: 'Top clientes por divida pendente', parameters: [{ name: 'top', in: 'query', schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },

    // ===== ARTIGOS =====
    '/artigos': { get: { tags: ['Artigos'], summary: 'Listar artigos', parameters: [
      { name: 'search', in: 'query', schema: { type: 'string' } },
      { name: 'familia', in: 'query', schema: { type: 'string' } },
      { name: 'comStock', in: 'query', schema: { type: 'string' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/artigos/{id}': { get: { tags: ['Artigos'], summary: 'Detalhes do artigo', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/artigos/{id}/movimentos': { get: { tags: ['Artigos'], summary: 'Movimentos de stock do artigo', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/artigos/{id}/fornecedores': { get: { tags: ['Artigos'], summary: 'Fornecedores do artigo', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/artigos/{id}/precos': { get: { tags: ['Artigos'], summary: 'Precos do artigo (PVP1-6, PCMedio, PCUltimo)', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/artigos/analytics/stock-baixo': { get: { tags: ['Artigos Analytics'], summary: 'Artigos abaixo stock minimo', responses: { 200: { description: 'OK' } } } },
    '/artigos/analytics/valor-stock': { get: { tags: ['Artigos Analytics'], summary: 'Valor total de inventario', responses: { 200: { description: 'OK' } } } },
    '/artigos/analytics/por-familia': { get: { tags: ['Artigos Analytics'], summary: 'Artigos e stock por familia', responses: { 200: { description: 'OK' } } } },

    // ===== VENDAS =====
    '/vendas/documentos': { get: { tags: ['Vendas'], summary: 'Listar documentos de venda (filtros avancados)', parameters: [
      { name: 'tipoDoc', in: 'query', schema: { type: 'string' }, description: 'Tipo documento (FA, EC, NC...)' },
      { name: 'cliente', in: 'query', schema: { type: 'string' }, description: 'Codigo do cliente' },
      { name: 'nome', in: 'query', schema: { type: 'string' }, description: 'Nome do cliente (LIKE)' },
      { name: 'vendedor', in: 'query', schema: { type: 'string' }, description: 'Codigo do vendedor' },
      { name: 'zona', in: 'query', schema: { type: 'string' }, description: 'Zona geografica' },
      { name: 'serie', in: 'query', schema: { type: 'string' } },
      { name: 'moeda', in: 'query', schema: { type: 'string' } },
      { name: 'condPag', in: 'query', schema: { type: 'string' }, description: 'Condicao pagamento' },
      { name: 'pais', in: 'query', schema: { type: 'string' } },
      { name: 'numDoc', in: 'query', schema: { type: 'integer' } },
      { name: 'numDocExterno', in: 'query', schema: { type: 'string' }, description: 'Numero documento externo (LIKE)' },
      { name: 'totalMin', in: 'query', schema: { type: 'number' }, description: 'Valor minimo' },
      { name: 'totalMax', in: 'query', schema: { type: 'number' }, description: 'Valor maximo' },
      { name: 'artigo', in: 'query', schema: { type: 'string' }, description: 'Filtrar por artigo (via linhas)' },
      { name: 'familia', in: 'query', schema: { type: 'string' }, description: 'Filtrar por familia de artigo (via linhas)' },
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/vendas/documentos/{id}': { get: { tags: ['Vendas'], summary: 'Documento com linhas', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/vendas/encomendas': { get: { tags: ['Vendas'], summary: 'Encomendas de cliente pendentes (EC)', responses: { 200: { description: 'OK' } } } },
    '/vendas/encomendas/{id}': { get: { tags: ['Vendas'], summary: 'Encomenda com linhas', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/mensal': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por mes', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/diario': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por dia', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/top-clientes': { get: { tags: ['Vendas Analytics'], summary: 'Top N clientes por facturacao', parameters: [{ name: 'top', in: 'query', schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/top-artigos': { get: { tags: ['Vendas Analytics'], summary: 'Top N artigos vendidos', parameters: [{ name: 'top', in: 'query', schema: { type: 'integer' } }, { name: 'por', in: 'query', schema: { type: 'string', enum: ['valor', 'quantidade'] } }], responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/por-vendedor': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por vendedor', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/por-familia': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por familia de artigos', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/por-zona': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por zona geografica', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/por-tipodoc': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por tipo de documento', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/por-localidade': { get: { tags: ['Vendas Analytics'], summary: 'Vendas por localidade com coordenadas', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'top', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/margens': { get: { tags: ['Vendas Analytics'], summary: 'Analise de margens por artigo', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/resumo': { get: { tags: ['Vendas Analytics'], summary: 'Resumo geral de vendas', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/yoy': { get: { tags: ['Vendas Analytics'], summary: 'Comparacao Year over Year', responses: { 200: { description: 'OK' } } } },
    '/vendas/analytics/geocode-cache': { get: { tags: ['Vendas Analytics'], summary: 'Estado da cache de geocoding', responses: { 200: { description: 'OK' } } } },

    // ===== COMPRAS =====
    '/compras/documentos': { get: { tags: ['Compras'], summary: 'Listar documentos de compra (filtros avancados)', parameters: [
      { name: 'tipoDoc', in: 'query', schema: { type: 'string' }, description: 'Tipo documento (VFA, ECF, VNC...)' },
      { name: 'fornecedor', in: 'query', schema: { type: 'string' }, description: 'Codigo do fornecedor' },
      { name: 'nome', in: 'query', schema: { type: 'string' }, description: 'Nome do fornecedor (LIKE) - ex: "Manuel"' },
      { name: 'serie', in: 'query', schema: { type: 'string' } },
      { name: 'moeda', in: 'query', schema: { type: 'string' } },
      { name: 'condPag', in: 'query', schema: { type: 'string' }, description: 'Condicao pagamento' },
      { name: 'numDoc', in: 'query', schema: { type: 'integer' } },
      { name: 'numDocExterno', in: 'query', schema: { type: 'string' }, description: 'Numero documento externo (LIKE)' },
      { name: 'totalMin', in: 'query', schema: { type: 'number' }, description: 'Valor minimo' },
      { name: 'totalMax', in: 'query', schema: { type: 'number' }, description: 'Valor maximo' },
      { name: 'artigo', in: 'query', schema: { type: 'string' }, description: 'Filtrar por artigo (via linhas)' },
      { name: 'familia', in: 'query', schema: { type: 'string' }, description: 'Filtrar por familia de artigo (via linhas)' },
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/compras/documentos/{id}': { get: { tags: ['Compras'], summary: 'Documento de compra com linhas', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/compras/encomendas': { get: { tags: ['Compras'], summary: 'Encomendas a fornecedor pendentes (ECF)', responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/mensal': { get: { tags: ['Compras Analytics'], summary: 'Compras por mes', responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/top-fornecedores': { get: { tags: ['Compras Analytics'], summary: 'Top fornecedores', responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/top-artigos': { get: { tags: ['Compras Analytics'], summary: 'Top artigos comprados', responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/resumo': { get: { tags: ['Compras Analytics'], summary: 'Resumo geral compras', responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/por-tipodoc': { get: { tags: ['Compras Analytics'], summary: 'Compras por tipo de documento', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/compras/analytics/yoy': { get: { tags: ['Compras Analytics'], summary: 'Comparacao Year over Year compras', responses: { 200: { description: 'OK' } } } },

    // ===== FORNECEDORES =====
    '/fornecedores': { get: { tags: ['Fornecedores'], summary: 'Listar fornecedores', parameters: [
      { name: 'search', in: 'query', schema: { type: 'string' }, description: 'Pesquisa geral (codigo, nome, contribuinte, email)' },
      { name: 'nome', in: 'query', schema: { type: 'string' }, description: 'Filtrar por nome' },
      { name: 'contribuinte', in: 'query', schema: { type: 'string' }, description: 'Filtrar por NIF' },
      { name: 'localidade', in: 'query', schema: { type: 'string' }, description: 'Filtrar por localidade' },
      { name: 'pais', in: 'query', schema: { type: 'string' }, description: 'Filtrar por pais' },
    ], responses: { 200: { description: 'OK' } } } },
    '/fornecedores/{id}': { get: { tags: ['Fornecedores'], summary: 'Detalhes fornecedor', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/fornecedores/{id}/documentos': { get: { tags: ['Fornecedores'], summary: 'Documentos de compra do fornecedor', parameters: [
      { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
      { name: 'tipoDoc', in: 'query', schema: { type: 'string' } },
      { name: 'serie', in: 'query', schema: { type: 'string' } },
      { name: 'totalMin', in: 'query', schema: { type: 'number' } },
      { name: 'totalMax', in: 'query', schema: { type: 'number' } },
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/fornecedores/{id}/saldo': { get: { tags: ['Fornecedores'], summary: 'Saldo conta corrente', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/fornecedores/{id}/artigos': { get: { tags: ['Fornecedores'], summary: 'Artigos fornecidos', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/fornecedores/analytics/resumo': { get: { tags: ['Fornecedores Analytics'], summary: 'Resumo geral fornecedores', responses: { 200: { description: 'OK' } } } },

    // ===== STOCK =====
    '/stock/actual': { get: { tags: ['Stock'], summary: 'Stock actual por artigo', responses: { 200: { description: 'OK' } } } },
    '/stock/por-armazem': { get: { tags: ['Stock'], summary: 'Stock agrupado por armazem', responses: { 200: { description: 'OK' } } } },
    '/stock/por-familia': { get: { tags: ['Stock'], summary: 'Stock por familia de artigos', responses: { 200: { description: 'OK' } } } },
    '/stock/por-localizacao': { get: { tags: ['Stock'], summary: 'Stock por localizacao', responses: { 200: { description: 'OK' } } } },
    '/stock/alertas': { get: { tags: ['Stock'], summary: 'Alertas de stock (abaixo minimo, sem stock)', responses: { 200: { description: 'OK' } } } },
    '/stock/movimentos': { get: { tags: ['Stock'], summary: 'Movimentos de stock', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/stock/rotacao': { get: { tags: ['Stock'], summary: 'Analise de rotacao de stock', parameters: [{ name: 'dias', in: 'query', schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/stock/resumo': { get: { tags: ['Stock'], summary: 'Resumo geral stock', responses: { 200: { description: 'OK' } } } },
    '/stock/numeros-serie': { get: { tags: ['Stock'], summary: 'Numeros de serie', parameters: [
      { name: 'artigo', in: 'query', schema: { type: 'string' } },
      { name: 'armazem', in: 'query', schema: { type: 'string' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/stock/transferencias': { get: { tags: ['Stock'], summary: 'Transferencias de stock', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/stock/transferencias/{id}': { get: { tags: ['Stock'], summary: 'Transferencia com linhas', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/stock/lotes': { get: { tags: ['Stock'], summary: 'Lotes de artigos', parameters: [{ name: 'artigo', in: 'query', schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },

    // ===== FINANCEIRO =====
    '/financeiro/contas': { get: { tags: ['Financeiro'], summary: 'Plano de contas', parameters: [{ name: 'search', in: 'query', schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/financeiro/movimentos': { get: { tags: ['Financeiro'], summary: 'Movimentos contabilisticos', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'page', in: 'query', schema: { type: 'integer' } },
      { name: 'limit', in: 'query', schema: { type: 'integer' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/financeiro/movimentos/{id}': { get: { tags: ['Financeiro'], summary: 'Movimento com linhas', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }], responses: { 200: { description: 'OK' } } } },
    '/financeiro/centros-custo': { get: { tags: ['Financeiro'], summary: 'Centros de custo', responses: { 200: { description: 'OK' } } } },
    '/financeiro/diarios': { get: { tags: ['Financeiro'], summary: 'Diarios contabilisticos', responses: { 200: { description: 'OK' } } } },
    '/financeiro/pendentes/clientes': { get: { tags: ['Financeiro Pendentes'], summary: 'Dividas de clientes', responses: { 200: { description: 'OK' } } } },
    '/financeiro/pendentes/fornecedores': { get: { tags: ['Financeiro Pendentes'], summary: 'Dividas a fornecedores', responses: { 200: { description: 'OK' } } } },
    '/financeiro/pendentes/aging': { get: { tags: ['Financeiro Pendentes'], summary: 'Aging report (antiguidade divida)', parameters: [{ name: 'tipo', in: 'query', schema: { type: 'string', enum: ['C', 'F'] } }], responses: { 200: { description: 'OK' } } } },
    '/financeiro/pendentes/resumo': { get: { tags: ['Financeiro Pendentes'], summary: 'Resumo a receber vs a pagar', responses: { 200: { description: 'OK' } } } },
    '/financeiro/pendentes/por-documento': { get: { tags: ['Financeiro Pendentes'], summary: 'Pendentes por tipo de documento', responses: { 200: { description: 'OK' } } } },
    '/financeiro/tesouraria/mensal': { get: { tags: ['Financeiro Tesouraria'], summary: 'Recebimentos vs pagamentos mensal', responses: { 200: { description: 'OK' } } } },
    '/financeiro/tesouraria/movimentos': { get: { tags: ['Financeiro Tesouraria'], summary: 'Movimentos de tesouraria', parameters: [
      { name: 'from', in: 'query', schema: { type: 'string', format: 'date' } },
      { name: 'to', in: 'query', schema: { type: 'string', format: 'date' } },
    ], responses: { 200: { description: 'OK' } } } },

    // ===== RH =====
    '/rh/funcionarios': { get: { tags: ['RH'], summary: 'Listar funcionarios', parameters: [
      { name: 'search', in: 'query', schema: { type: 'string' } },
      { name: 'departamento', in: 'query', schema: { type: 'string' } },
      { name: 'situacao', in: 'query', schema: { type: 'string' } },
    ], responses: { 200: { description: 'OK' } } } },
    '/rh/funcionarios/{id}': { get: { tags: ['RH'], summary: 'Detalhes do funcionario', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'OK' } } } },
    '/rh/departamentos': { get: { tags: ['RH'], summary: 'Departamentos com headcount', responses: { 200: { description: 'OK' } } } },
    '/rh/analytics/resumo': { get: { tags: ['RH Analytics'], summary: 'Resumo RH', responses: { 200: { description: 'OK' } } } },
    '/rh/analytics/por-departamento': { get: { tags: ['RH Analytics'], summary: 'Analise por departamento', responses: { 200: { description: 'OK' } } } },
    '/rh/analytics/antiguidade': { get: { tags: ['RH Analytics'], summary: 'Distribuicao por antiguidade', responses: { 200: { description: 'OK' } } } },
    '/rh/analytics/por-situacao': { get: { tags: ['RH Analytics'], summary: 'Funcionarios por situacao', responses: { 200: { description: 'OK' } } } },
    '/rh/analytics/vencimentos': { get: { tags: ['RH Analytics'], summary: 'Distribuicao de vencimentos', responses: { 200: { description: 'OK' } } } },

    // ===== QUERY LIVRE =====
    '/query': { post: { tags: ['Query Livre'], summary: 'Executar query SQL read-only (para LLM)', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { sql: { type: 'string', example: "SELECT TOP 10 * FROM Clientes" } }, required: ['sql'] } } } }, responses: { 200: { description: 'OK' }, 403: { description: 'Operacao bloqueada' } } } },

    // ===== COPILOT =====
    '/copilot/context': { get: { tags: ['Copilot'], summary: 'Contexto da API para LLM', responses: { 200: { description: 'OK' } } } },
  },
};

module.exports = swaggerDoc;
